SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM (
    SELECT FOOD_TYPE, 
    REST_ID, 
    REST_NAME, 
    FAVORITES, 
    ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RN
    FROM REST_INFO
) A
WHERE RN = 1
ORDER BY A.FOOD_TYPE DESC
