SELECT YEAR(OS.SALES_DATE) AS YEAR, 
MONTH(OS.SALES_DATE) AS MONTH, 
UI.GENDER AS GENDER, 
COUNT(DISTINCT UI.USER_ID) AS USERS
FROM ONLINE_SALE OS
INNER JOIN USER_INFO UI
ON UI.USER_ID = OS.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), UI.GENDER
ORDER BY YEAR, MONTH, GENDER
