WITH RECURSIVE RC AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H + 1
    FROM RC
    WHERE H < 23
)

SELECT RC.H AS HOUR, COALESCE(A.COUNT, 0) AS COUNT
FROM RC
LEFT JOIN (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
ORDER BY HOUR) A
ON RC.H = A.HOUR
ORDER BY HOUR
