SELECT A.ID, FNI.FISH_NAME, A.LENGTH
FROM(
SELECT ID
    , FISH_TYPE
    , LENGTH
    , ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS FISH_RANK
FROM FISH_INFO
) A
INNER JOIN FISH_NAME_INFO FNI
ON A.FISH_TYPE = FNI.FISH_TYPE
WHERE A.FISH_RANK = 1
ORDER BY A.ID
