SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, PRODUCT_NAME, ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) RN
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ( '과자', '국', '김치', '식용유')
) A
WHERE A.RN = 1
ORDER BY A.PRICE DESC